use_frameworks!

target 'DateScrollPicker_Example' do
  pod 'DateScrollPicker', :path => '../'

  target 'DateScrollPicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
